name: Tag releases on PR closing

on:
  pull_request:
    types: [ 'closed' ]
    branches: [ 'main' ]

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: '[MAJOR]'
          MINOR_STRING_TOKEN: '[MINOR]'
          PATCH_STRING_TOKEN: '[PATCH]'
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}

  release:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/distributions/*"
          tag: ${{ needs.bump.outputs.new_tag }}

